//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfColorFont.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfColorFont.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        public static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AliceBlue;#FFF0F8FF.
        /// </summary>
        public static string IdColorAliceBlue {
            get {
                return ResourceManager.GetString("IdColorAliceBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntiqueWhite;#FFFAEBD7.
        /// </summary>
        public static string IdColorAntiqueWhite {
            get {
                return ResourceManager.GetString("IdColorAntiqueWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua;#FF00FFFF.
        /// </summary>
        public static string IdColorAqua {
            get {
                return ResourceManager.GetString("IdColorAqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquamarine;#FF7FFFD4.
        /// </summary>
        public static string IdColorAquamarine {
            get {
                return ResourceManager.GetString("IdColorAquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure;#FFF0FFFF.
        /// </summary>
        public static string IdColorAzure {
            get {
                return ResourceManager.GetString("IdColorAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige;#FFF5F5DC.
        /// </summary>
        public static string IdColorBeige {
            get {
                return ResourceManager.GetString("IdColorBeige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisque;#FFFFE4C4.
        /// </summary>
        public static string IdColorBisque {
            get {
                return ResourceManager.GetString("IdColorBisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black;#FF000000.
        /// </summary>
        public static string IdColorBlack {
            get {
                return ResourceManager.GetString("IdColorBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlanchedAlmond;#FFFFEBCD.
        /// </summary>
        public static string IdColorBlanchedAlmond {
            get {
                return ResourceManager.GetString("IdColorBlanchedAlmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue;#FF0000FF.
        /// </summary>
        public static string IdColorBlue {
            get {
                return ResourceManager.GetString("IdColorBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueViolet;#FF8A2BE2.
        /// </summary>
        public static string IdColorBlueViolet {
            get {
                return ResourceManager.GetString("IdColorBlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown;#FFA52A2A.
        /// </summary>
        public static string IdColorBrown {
            get {
                return ResourceManager.GetString("IdColorBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BurlyWood;#FFDEB887.
        /// </summary>
        public static string IdColorBurlyWood {
            get {
                return ResourceManager.GetString("IdColorBurlyWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CadetBlue;#FF5F9EA0.
        /// </summary>
        public static string IdColorCadetBlue {
            get {
                return ResourceManager.GetString("IdColorCadetBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chartreuse;#FF7FFF00.
        /// </summary>
        public static string IdColorChartreuse {
            get {
                return ResourceManager.GetString("IdColorChartreuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate;#FFD2691E.
        /// </summary>
        public static string IdColorChocolate {
            get {
                return ResourceManager.GetString("IdColorChocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coral;#FFFF7F50.
        /// </summary>
        public static string IdColorCoral {
            get {
                return ResourceManager.GetString("IdColorCoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CornflowerBlue;#FF6495ED.
        /// </summary>
        public static string IdColorCornflowerBlue {
            get {
                return ResourceManager.GetString("IdColorCornflowerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cornsilk;#FFFFF8DC.
        /// </summary>
        public static string IdColorCornsilk {
            get {
                return ResourceManager.GetString("IdColorCornsilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crimson;#FFDC143C.
        /// </summary>
        public static string IdColorCrimson {
            get {
                return ResourceManager.GetString("IdColorCrimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan;#FF00FFFF.
        /// </summary>
        public static string IdColorCyan {
            get {
                return ResourceManager.GetString("IdColorCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkBlue;#FF00008B.
        /// </summary>
        public static string IdColorDarkBlue {
            get {
                return ResourceManager.GetString("IdColorDarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkCyan;#FF008B8B.
        /// </summary>
        public static string IdColorDarkCyan {
            get {
                return ResourceManager.GetString("IdColorDarkCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGoldenrod;#FFB8860B.
        /// </summary>
        public static string IdColorDarkGoldenrod {
            get {
                return ResourceManager.GetString("IdColorDarkGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGray;#FFA9A9A9.
        /// </summary>
        public static string IdColorDarkGray {
            get {
                return ResourceManager.GetString("IdColorDarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkGreen;#FF006400.
        /// </summary>
        public static string IdColorDarkGreen {
            get {
                return ResourceManager.GetString("IdColorDarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkKhaki;#FFBDB76B.
        /// </summary>
        public static string IdColorDarkKhaki {
            get {
                return ResourceManager.GetString("IdColorDarkKhaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkMagenta;#FF8B008B.
        /// </summary>
        public static string IdColorDarkMagenta {
            get {
                return ResourceManager.GetString("IdColorDarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkOliveGreen;#FF556B2F.
        /// </summary>
        public static string IdColorDarkOliveGreen {
            get {
                return ResourceManager.GetString("IdColorDarkOliveGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkOrange;#FFFF8C00.
        /// </summary>
        public static string IdColorDarkOrange {
            get {
                return ResourceManager.GetString("IdColorDarkOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkOrchid;#FF9932CC.
        /// </summary>
        public static string IdColorDarkOrchid {
            get {
                return ResourceManager.GetString("IdColorDarkOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkRed;#FF8B0000.
        /// </summary>
        public static string IdColorDarkRed {
            get {
                return ResourceManager.GetString("IdColorDarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkSalmon;#FFE9967A.
        /// </summary>
        public static string IdColorDarkSalmon {
            get {
                return ResourceManager.GetString("IdColorDarkSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkSeaGreen;#FF8FBC8B.
        /// </summary>
        public static string IdColorDarkSeaGreen {
            get {
                return ResourceManager.GetString("IdColorDarkSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkSlateBlue;#FF483D8B.
        /// </summary>
        public static string IdColorDarkSlateBlue {
            get {
                return ResourceManager.GetString("IdColorDarkSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkSlateGray;#FF2F4F4F.
        /// </summary>
        public static string IdColorDarkSlateGray {
            get {
                return ResourceManager.GetString("IdColorDarkSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkTurquoise;#FF00CED1.
        /// </summary>
        public static string IdColorDarkTurquoise {
            get {
                return ResourceManager.GetString("IdColorDarkTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkViolet;#FF9400D3.
        /// </summary>
        public static string IdColorDarkViolet {
            get {
                return ResourceManager.GetString("IdColorDarkViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepPink;#FFFF1493.
        /// </summary>
        public static string IdColorDeepPink {
            get {
                return ResourceManager.GetString("IdColorDeepPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepSkyBlue;#FF00BFFF.
        /// </summary>
        public static string IdColorDeepSkyBlue {
            get {
                return ResourceManager.GetString("IdColorDeepSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DimGray;#FF696969.
        /// </summary>
        public static string IdColorDimGray {
            get {
                return ResourceManager.GetString("IdColorDimGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DodgerBlue;#FF1E90FF.
        /// </summary>
        public static string IdColorDodgerBlue {
            get {
                return ResourceManager.GetString("IdColorDodgerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebrick;#FFB22222.
        /// </summary>
        public static string IdColorFirebrick {
            get {
                return ResourceManager.GetString("IdColorFirebrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FloralWhite;#FFFFFAF0.
        /// </summary>
        public static string IdColorFloralWhite {
            get {
                return ResourceManager.GetString("IdColorFloralWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForestGreen;#FF228B22.
        /// </summary>
        public static string IdColorForestGreen {
            get {
                return ResourceManager.GetString("IdColorForestGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuchsia;#FFFF00FF.
        /// </summary>
        public static string IdColorFuchsia {
            get {
                return ResourceManager.GetString("IdColorFuchsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gainsboro;#FFDCDCDC.
        /// </summary>
        public static string IdColorGainsboro {
            get {
                return ResourceManager.GetString("IdColorGainsboro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GhostWhite;#FFF8F8FF.
        /// </summary>
        public static string IdColorGhostWhite {
            get {
                return ResourceManager.GetString("IdColorGhostWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold;#FFFFD700.
        /// </summary>
        public static string IdColorGold {
            get {
                return ResourceManager.GetString("IdColorGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goldenrod;#FFDAA520.
        /// </summary>
        public static string IdColorGoldenrod {
            get {
                return ResourceManager.GetString("IdColorGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray;#FF808080.
        /// </summary>
        public static string IdColorGray {
            get {
                return ResourceManager.GetString("IdColorGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green;#FF008000.
        /// </summary>
        public static string IdColorGreen {
            get {
                return ResourceManager.GetString("IdColorGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreenYellow;#FFADFF2F.
        /// </summary>
        public static string IdColorGreenYellow {
            get {
                return ResourceManager.GetString("IdColorGreenYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honeydew;#FFF0FFF0.
        /// </summary>
        public static string IdColorHoneydew {
            get {
                return ResourceManager.GetString("IdColorHoneydew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotPink;#FFFF69B4.
        /// </summary>
        public static string IdColorHotPink {
            get {
                return ResourceManager.GetString("IdColorHotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndianRed;#FFCD5C5C.
        /// </summary>
        public static string IdColorIndianRed {
            get {
                return ResourceManager.GetString("IdColorIndianRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo;#FF4B0082.
        /// </summary>
        public static string IdColorIndigo {
            get {
                return ResourceManager.GetString("IdColorIndigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivory;#FFFFFFF0.
        /// </summary>
        public static string IdColorIvory {
            get {
                return ResourceManager.GetString("IdColorIvory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khaki;#FFF0E68C.
        /// </summary>
        public static string IdColorKhaki {
            get {
                return ResourceManager.GetString("IdColorKhaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender;#FFE6E6FA.
        /// </summary>
        public static string IdColorLavender {
            get {
                return ResourceManager.GetString("IdColorLavender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LavenderBlush;#FFFFF0F5.
        /// </summary>
        public static string IdColorLavenderBlush {
            get {
                return ResourceManager.GetString("IdColorLavenderBlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LawnGreen;#FF7CFC00.
        /// </summary>
        public static string IdColorLawnGreen {
            get {
                return ResourceManager.GetString("IdColorLawnGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LemonChiffon;#FFFFFACD.
        /// </summary>
        public static string IdColorLemonChiffon {
            get {
                return ResourceManager.GetString("IdColorLemonChiffon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightBlue;#FFADD8E6.
        /// </summary>
        public static string IdColorLightBlue {
            get {
                return ResourceManager.GetString("IdColorLightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightCoral;#FFF08080.
        /// </summary>
        public static string IdColorLightCoral {
            get {
                return ResourceManager.GetString("IdColorLightCoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightCyan;#FFE0FFFF.
        /// </summary>
        public static string IdColorLightCyan {
            get {
                return ResourceManager.GetString("IdColorLightCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGoldenrodYellow;#FFFAFAD2.
        /// </summary>
        public static string IdColorLightGoldenrodYellow {
            get {
                return ResourceManager.GetString("IdColorLightGoldenrodYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGray;#FFD3D3D3.
        /// </summary>
        public static string IdColorLightGray {
            get {
                return ResourceManager.GetString("IdColorLightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGreen;#FF90EE90.
        /// </summary>
        public static string IdColorLightGreen {
            get {
                return ResourceManager.GetString("IdColorLightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightPink;#FFFFB6C1.
        /// </summary>
        public static string IdColorLightPink {
            get {
                return ResourceManager.GetString("IdColorLightPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSalmon;#FFFFA07A.
        /// </summary>
        public static string IdColorLightSalmon {
            get {
                return ResourceManager.GetString("IdColorLightSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSeaGreen;#FF20B2AA.
        /// </summary>
        public static string IdColorLightSeaGreen {
            get {
                return ResourceManager.GetString("IdColorLightSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSkyBlue;#FF87CEFA.
        /// </summary>
        public static string IdColorLightSkyBlue {
            get {
                return ResourceManager.GetString("IdColorLightSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSlateGray;#FF778899.
        /// </summary>
        public static string IdColorLightSlateGray {
            get {
                return ResourceManager.GetString("IdColorLightSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightSteelBlue;#FFB0C4DE.
        /// </summary>
        public static string IdColorLightSteelBlue {
            get {
                return ResourceManager.GetString("IdColorLightSteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightYellow;#FFFFFFE0.
        /// </summary>
        public static string IdColorLightYellow {
            get {
                return ResourceManager.GetString("IdColorLightYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime;#FF00FF00.
        /// </summary>
        public static string IdColorLime {
            get {
                return ResourceManager.GetString("IdColorLime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LimeGreen;#FF32CD32.
        /// </summary>
        public static string IdColorLimeGreen {
            get {
                return ResourceManager.GetString("IdColorLimeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linen;#FFFAF0E6.
        /// </summary>
        public static string IdColorLinen {
            get {
                return ResourceManager.GetString("IdColorLinen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta;#FFFF00FF.
        /// </summary>
        public static string IdColorMagenta {
            get {
                return ResourceManager.GetString("IdColorMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maroon;#FF800000.
        /// </summary>
        public static string IdColorMaroon {
            get {
                return ResourceManager.GetString("IdColorMaroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumAquamarine;#FF66CDAA.
        /// </summary>
        public static string IdColorMediumAquamarine {
            get {
                return ResourceManager.GetString("IdColorMediumAquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumBlue;#FF0000CD.
        /// </summary>
        public static string IdColorMediumBlue {
            get {
                return ResourceManager.GetString("IdColorMediumBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumOrchid;#FFBA55D3.
        /// </summary>
        public static string IdColorMediumOrchid {
            get {
                return ResourceManager.GetString("IdColorMediumOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumPurple;#FF9370DB.
        /// </summary>
        public static string IdColorMediumPurple {
            get {
                return ResourceManager.GetString("IdColorMediumPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumSeaGreen;#FF3CB371.
        /// </summary>
        public static string IdColorMediumSeaGreen {
            get {
                return ResourceManager.GetString("IdColorMediumSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumSlateBlue;#FF7B68EE.
        /// </summary>
        public static string IdColorMediumSlateBlue {
            get {
                return ResourceManager.GetString("IdColorMediumSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumSpringGreen;#FF00FA9A.
        /// </summary>
        public static string IdColorMediumSpringGreen {
            get {
                return ResourceManager.GetString("IdColorMediumSpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumTurquoise;#FF48D1CC.
        /// </summary>
        public static string IdColorMediumTurquoise {
            get {
                return ResourceManager.GetString("IdColorMediumTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediumVioletRed;#FFC71585.
        /// </summary>
        public static string IdColorMediumVioletRed {
            get {
                return ResourceManager.GetString("IdColorMediumVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MidnightBlue;#FF191970.
        /// </summary>
        public static string IdColorMidnightBlue {
            get {
                return ResourceManager.GetString("IdColorMidnightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MintCream;#FFF5FFFA.
        /// </summary>
        public static string IdColorMintCream {
            get {
                return ResourceManager.GetString("IdColorMintCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MistyRose;#FFFFE4E1.
        /// </summary>
        public static string IdColorMistyRose {
            get {
                return ResourceManager.GetString("IdColorMistyRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moccasin;#FFFFE4B5.
        /// </summary>
        public static string IdColorMoccasin {
            get {
                return ResourceManager.GetString("IdColorMoccasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavajoWhite;#FFFFDEAD.
        /// </summary>
        public static string IdColorNavajoWhite {
            get {
                return ResourceManager.GetString("IdColorNavajoWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy;#FF000080.
        /// </summary>
        public static string IdColorNavy {
            get {
                return ResourceManager.GetString("IdColorNavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldLace;#FFFDF5E6.
        /// </summary>
        public static string IdColorOldLace {
            get {
                return ResourceManager.GetString("IdColorOldLace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive;#FF808000.
        /// </summary>
        public static string IdColorOlive {
            get {
                return ResourceManager.GetString("IdColorOlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OliveDrab;#FF6B8E23.
        /// </summary>
        public static string IdColorOliveDrab {
            get {
                return ResourceManager.GetString("IdColorOliveDrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange;#FFFFA500.
        /// </summary>
        public static string IdColorOrange {
            get {
                return ResourceManager.GetString("IdColorOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrangeRed;#FFFF4500.
        /// </summary>
        public static string IdColorOrangeRed {
            get {
                return ResourceManager.GetString("IdColorOrangeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchid;#FFDA70D6.
        /// </summary>
        public static string IdColorOrchid {
            get {
                return ResourceManager.GetString("IdColorOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaleGoldenrod;#FFEEE8AA.
        /// </summary>
        public static string IdColorPaleGoldenrod {
            get {
                return ResourceManager.GetString("IdColorPaleGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaleGreen;#FF98FB98.
        /// </summary>
        public static string IdColorPaleGreen {
            get {
                return ResourceManager.GetString("IdColorPaleGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaleTurquoise;#FFAFEEEE.
        /// </summary>
        public static string IdColorPaleTurquoise {
            get {
                return ResourceManager.GetString("IdColorPaleTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaleVioletRed;#FFDB7093.
        /// </summary>
        public static string IdColorPaleVioletRed {
            get {
                return ResourceManager.GetString("IdColorPaleVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PapayaWhip;#FFFFEFD5.
        /// </summary>
        public static string IdColorPapayaWhip {
            get {
                return ResourceManager.GetString("IdColorPapayaWhip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeachPuff;#FFFFDAB9.
        /// </summary>
        public static string IdColorPeachPuff {
            get {
                return ResourceManager.GetString("IdColorPeachPuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru;#FFCD853F.
        /// </summary>
        public static string IdColorPeru {
            get {
                return ResourceManager.GetString("IdColorPeru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink;#FFFFC0CB.
        /// </summary>
        public static string IdColorPink {
            get {
                return ResourceManager.GetString("IdColorPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plum;#FFDDA0DD.
        /// </summary>
        public static string IdColorPlum {
            get {
                return ResourceManager.GetString("IdColorPlum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowderBlue;#FFB0E0E6.
        /// </summary>
        public static string IdColorPowderBlue {
            get {
                return ResourceManager.GetString("IdColorPowderBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple;#FF800080.
        /// </summary>
        public static string IdColorPurple {
            get {
                return ResourceManager.GetString("IdColorPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red;#FFFF0000.
        /// </summary>
        public static string IdColorRed {
            get {
                return ResourceManager.GetString("IdColorRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RosyBrown;#FFBC8F8F.
        /// </summary>
        public static string IdColorRosyBrown {
            get {
                return ResourceManager.GetString("IdColorRosyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoyalBlue;#FF4169E1.
        /// </summary>
        public static string IdColorRoyalBlue {
            get {
                return ResourceManager.GetString("IdColorRoyalBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaddleBrown;#FF8B4513.
        /// </summary>
        public static string IdColorSaddleBrown {
            get {
                return ResourceManager.GetString("IdColorSaddleBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salmon;#FFFA8072.
        /// </summary>
        public static string IdColorSalmon {
            get {
                return ResourceManager.GetString("IdColorSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SandyBrown;#FFF4A460.
        /// </summary>
        public static string IdColorSandyBrown {
            get {
                return ResourceManager.GetString("IdColorSandyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeaGreen;#FF2E8B57.
        /// </summary>
        public static string IdColorSeaGreen {
            get {
                return ResourceManager.GetString("IdColorSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeaShell;#FFFFF5EE.
        /// </summary>
        public static string IdColorSeaShell {
            get {
                return ResourceManager.GetString("IdColorSeaShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sienna;#FFA0522D.
        /// </summary>
        public static string IdColorSienna {
            get {
                return ResourceManager.GetString("IdColorSienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver;#FFC0C0C0.
        /// </summary>
        public static string IdColorSilver {
            get {
                return ResourceManager.GetString("IdColorSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyBlue;#FF87CEEB.
        /// </summary>
        public static string IdColorSkyBlue {
            get {
                return ResourceManager.GetString("IdColorSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlateBlue;#FF6A5ACD.
        /// </summary>
        public static string IdColorSlateBlue {
            get {
                return ResourceManager.GetString("IdColorSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlateGray;#FF708090.
        /// </summary>
        public static string IdColorSlateGray {
            get {
                return ResourceManager.GetString("IdColorSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow;#FFFFFAFA.
        /// </summary>
        public static string IdColorSnow {
            get {
                return ResourceManager.GetString("IdColorSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpringGreen;#FF00FF7F.
        /// </summary>
        public static string IdColorSpringGreen {
            get {
                return ResourceManager.GetString("IdColorSpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteelBlue;#FF4682B4.
        /// </summary>
        public static string IdColorSteelBlue {
            get {
                return ResourceManager.GetString("IdColorSteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan;#FFD2B48C.
        /// </summary>
        public static string IdColorTan {
            get {
                return ResourceManager.GetString("IdColorTan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal;#FF008080.
        /// </summary>
        public static string IdColorTeal {
            get {
                return ResourceManager.GetString("IdColorTeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thistle;#FFD8BFD8.
        /// </summary>
        public static string IdColorThistle {
            get {
                return ResourceManager.GetString("IdColorThistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomato;#FFFF6347.
        /// </summary>
        public static string IdColorTomato {
            get {
                return ResourceManager.GetString("IdColorTomato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise;#FF40E0D0.
        /// </summary>
        public static string IdColorTurquoise {
            get {
                return ResourceManager.GetString("IdColorTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet;#FFEE82EE.
        /// </summary>
        public static string IdColorViolet {
            get {
                return ResourceManager.GetString("IdColorViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat;#FFF5DEB3.
        /// </summary>
        public static string IdColorWheat {
            get {
                return ResourceManager.GetString("IdColorWheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White;#FFFFFFFF.
        /// </summary>
        public static string IdColorWhite {
            get {
                return ResourceManager.GetString("IdColorWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhiteSmoke;#FFF5F5F5.
        /// </summary>
        public static string IdColorWhiteSmoke {
            get {
                return ResourceManager.GetString("IdColorWhiteSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow;#FFFFFF00.
        /// </summary>
        public static string IdColorYellow {
            get {
                return ResourceManager.GetString("IdColorYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YellowGreen;#FF9ACD32.
        /// </summary>
        public static string IdColorYellowGreen {
            get {
                return ResourceManager.GetString("IdColorYellowGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Text.
        /// </summary>
        public static string SampleText {
            get {
                return ResourceManager.GetString("SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style - Weight.
        /// </summary>
        public static string StyleWeight {
            get {
                return ResourceManager.GetString("StyleWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Font.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
